version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Run tests
          command: bundle exec rspec
